# Supabase Configuration for Ask Ed
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://heyed.co.uk"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
major_version = 15

[functions]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
image_transformation = {
  enabled = true
}

[edge_runtime]
enabled = true
port = 54325

[analytics]
enabled = false

[inbound_mail]
enabled = false